# Generated by Django 4.2 on 2025-03-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortenerapp', '0002_alter_urlmodel_shorturl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='completeUrl',
            field=models.URLField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='urlmodel',
            name='shortUrl',
            field=models.CharField(editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='urlmodel',
            name='visitorIp',
            field=models.GenericIPAddressField(blank=True, editable=False, null=True),
        ),
    ]
