# Generated by Django 4.2 on 2025-03-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortenerapp', '0003_alter_urlmodel_completeurl_alter_urlmodel_shorturl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='completeUrl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urlmodel',
            name='longUrl',
            field=models.CharField(max_length=23000),
        ),
        migrations.AlterField(
            model_name='urlmodel',
            name='shortUrl',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='urlmodel',
            name='visitorIp',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
