# Generated by Django 4.2 on 2025-03-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortenerapp', '0004_alter_urlmodel_completeurl_alter_urlmodel_longurl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='longUrl',
            field=models.URLField(max_length=23000),
        ),
    ]
