# Generated by Django 4.2 on 2025-03-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortenerapp', '0007_alter_urlmodel_longurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='longUrl',
            field=models.CharField(max_length=23000),
        ),
    ]
